Init Commit
DrexelSmartHouse/DSHouse-Login-Auto pull request #1
Opened 2018-07-11 06:22 UTC by robotrampage15

2018-07-12 17:00 UTC, jcohen98 requested changes

2018-07-12 17:00 UTC, jcohen98 commented on sendEmail.py
> +				<title>*|MC:SUBJECT|*</title>
This title shows up as |MC:SUBJECT| when you send the email. Can we change this?

2018-07-12 17:00 UTC, jcohen98 commented on sendEmail.py
> +					/*@editable*/font-weight:normal;
Why are there all these commented out @editable tags?

2018-07-12 17:00 UTC, jcohen98 commented on sendEmail.py
> +	s.login('info@drexelsmarthouse.com','***************')
Instead of filling this in through the script itself, best practice is to read from some sort of config or .properties file. There are many different ways to do this and file types you can use. If you need, I have a python class already written for this

2018-07-12 17:00 UTC, jcohen98 commented on testScript.py
> +	rootA.title('Scan Card')
Is there an easy way to always keep the card access window on top of all other windows? Whenever we have another screen open, like a grafana dashboard, when a new window is made (EX: The "You signed in" window), it appears behind the open web browser

2018-07-12 17:00 UTC, jcohen98 commented on testScript.py
> +	credentials = ServiceAccountCredentials.from_json_keyfile_name('creds.json', scope)
Seems like you did the proper thing with credentials down here

2018-07-17 04:34 UTC, robotrampage15 commented
All solutions have been added, a secondary file is needed for all links and passwords

2018-07-17 16:47 UTC, jcohen98 requested changes

2018-07-17 16:47 UTC, jcohen98 commented on sendEmail.py
> +#!usr/bin/emv python
Need to change the emv to "env"

2018-07-17 16:47 UTC, jcohen98 commented on testScript.py
> +#!usr/bin/emv python
again change emv to env

2018-07-17 16:56 UTC, jcohen98 commented on sendEmail.py
> +#!usr/bin/emv python
The full line should be #!/usr/bin/env python

2018-07-17 16:56 UTC, jcohen98 commented on testScript.py
> +#!usr/bin/emv python
The full line should be #!/usr/bin/env python

2018-07-17 19:32 UTC, robotrampage15 commented
changes made, "emv" to "env"

2018-07-17 19:36 UTC, jcohen98 approved these changes

2018-07-17 19:36 UTC, merged